//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventsXamarin.AppResources.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventsXamarin.AppResources.Localizations.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attend.
        /// </summary>
        public static string Attend_Btn {
            get {
                return ResourceManager.GetString("Attend_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re going to this event.
        /// </summary>
        public static string Attended_Lbl {
            get {
                return ResourceManager.GetString("Attended_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel_Btn {
            get {
                return ResourceManager.GetString("Cancel_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cat Facts.
        /// </summary>
        public static string Cat_Facts_Title {
            get {
                return ResourceManager.GetString("Cat_Facts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close_Btn {
            get {
                return ResourceManager.GetString("Close_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete_Btn {
            get {
                return ResourceManager.GetString("Delete_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string Delete_Error_Message_Toast {
            get {
                return ResourceManager.GetString("Delete_Error_Message_Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll permanently lose your event data..
        /// </summary>
        public static string Delete_Event_Confirm_Message_Lbl {
            get {
                return ResourceManager.GetString("Delete_Event_Confirm_Message_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Event?.
        /// </summary>
        public static string Delete_Event_Lbl {
            get {
                return ResourceManager.GetString("Delete_Event_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event deleted successfully.
        /// </summary>
        public static string Delete_Success_Message_Toast {
            get {
                return ResourceManager.GetString("Delete_Success_Message_Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Event_Title {
            get {
                return ResourceManager.GetString("Event_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, please try again later.
        /// </summary>
        public static string General_Error_Message {
            get {
                return ResourceManager.GetString("General_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to going.
        /// </summary>
        public static string Going_Lbl {
            get {
                return ResourceManager.GetString("Going_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check internet connection, then try again.
        /// </summary>
        public static string Internet_Connection_Message {
            get {
                return ResourceManager.GetString("Internet_Connection_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No map application available to open.
        /// </summary>
        public static string No_App_Map_Available_Message {
            get {
                return ResourceManager.GetString("No_App_Map_Available_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data.
        /// </summary>
        public static string No_Data_Lbl {
            get {
                return ResourceManager.GetString("No_Data_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People are going.
        /// </summary>
        public static string People_Going_Lbl {
            get {
                return ResourceManager.GetString("People_Going_Lbl", resourceCulture);
            }
        }
    }
}
